font_family Hasklug Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13
#hide_window_decorations true
#wayland_titlebar_color background

#symbol_map U+E000-U+F8FF AurulentSansM Nerd Font Propo

foreground white
background #0c0d12
background_opacity 0.85
background_blur 1
