music_directory    "/home/billu/Music"
playlist_directory "/home/billu/Music/playlists"

auto_update "yes"
restore_paused "yes"

audio_output {
        type            "pipewire"
        name            "mpdpipewire"
}
