[font]

normal = { family = "Hasklug Nerd Font", style = "Regular" }
bold = { family = "Hasklug Nerd Font", style = "Bold" }
italic = { family = "Hasklug Nerd Font", style = "Italic" }
bold_italic = { family = "Hasklug Nerd Font", style = "Bold Italic" }

size = 13.0
#glyph_offset = { x = 0, y = 0 }

builtin_box_drawing = true

[colors.primary]

background = "#0c0d12"

[window]

opacity = 0.85
